#!/usr/bin/env sh

# Kill all sessions for $1 user.
pkill -KILL -u $1

if [ $? -eq 0 ] # if sessions got killed
then
    # Now that all the sessions have been killed, delete the user.
    userdel -rf $1
fi
